INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('543-30-01730-32-4', 'Colleen Franks', 8, 'Hamlet', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('753-07-66350-00-2', 'Hazel Judd', 1, 'Vanity Fai', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('707-17-50350-83-8', 'Penelope Rainford', 4, 'Paradise L', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('553-55-62817-11-3', 'Carolyn Walton', 6, 'Moby Dick', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('536-31-35600-02-2', 'Selena Lloyd', 6, 'Pride and ', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('135-67-53853-14-1', 'Ethan Bailey', 5, 'To the Lig', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('220-01-80574-78-1', 'Elena Styles', 3, 'The Odysse', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('876-30-28480-60-3', 'Elijah Sanchez', 7, 'Hamlet', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('377-85-36483-53-4', 'Logan Weasley', 4, 'The Canter', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('072-41-40436-60-3', 'Tiffany Kennedy', 10, 'The Handma', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('182-68-03613-82-8', 'Michael Hamilton', 9, 'The Old Ma', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('644-83-72316-68-5', 'Denis Wright', 4, 'Alice Adve', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('236-67-03364-04-2', 'Caleb Osmond', 2, 'The Flower', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('876-61-83423-20-3', 'Molly Janes', 11, 'Paradise L', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('588-34-81243-13-3', 'Rocco Holmes', 9, 'Gulliver''s', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('574-41-04350-86-4', 'Camila James', 8, 'The Metamo', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('160-58-01882-44-0', 'Barry Vangness', 5, 'Invisible ', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('730-44-25658-76-7', 'Bethany Savage', 5, 'Don Quixot', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('430-04-11474-21-5', 'Carter Adler', 3, 'One Hundre', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('532-34-01465-26-2', 'Candace Jackson', 3, 'Alice Adve', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('533-67-23717-16-6', 'Nicholas Holmes', 5, 'Ulysses', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('482-54-85682-82-6', 'Denny Button', 1, 'Lord of th', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('410-20-54744-48-7', 'Nathan Alcroft', 8, 'Anna Karen', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('862-43-41443-06-8', 'Joseph Forth', 8, 'The Scarle', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('208-00-24318-61-2', 'Anais Flack', 8, 'Madame Bov', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('667-08-33651-65-0', 'Lily Whitmore', 8, 'Emma', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('128-10-57273-74-1', 'Chad Jennson', 8, 'Invisible ', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('856-58-13253-43-3', 'Anais Dyson', 11, 'Vanity Fai', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('741-15-26651-88-7', 'Scarlett Whinter', 6, 'The Flower', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('005-31-83041-72-7', 'Regina Shepherd', 8, 'One Thousa', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('121-46-06357-53-2', 'Ron Connor', 6, 'To Kill a ', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('811-12-47808-40-3', 'Bridget Malone', 2, 'The Magic ', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('724-56-27745-13-7', 'Leroy Morrow', 7, 'The Divine', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('788-15-41722-63-2', 'Rocco Alcroft', 1, 'The Red an', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('483-62-28556-02-1', 'Lucas Bolton', 7, 'One Hundre', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('705-45-57274-87-3', 'Nate Haines', 2, 'The Divine', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('676-84-01848-07-3', 'Maya Rixon', 3, 'Tristram S', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('714-81-06858-48-1', 'Rosie Mcgregor', 6, 'The Divine', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('034-52-36642-66-1', 'Bob Evans', 3, 'The Canter', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('476-04-80872-02-3', 'Chris Keys', 10, 'Moby Dick', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('253-31-58223-58-2', 'Aileen Cox', 6, 'Great Expe', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('861-38-44821-76-4', 'Brad Nelson', 4, 'Nineteen E', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('545-66-42263-07-8', 'Marjorie Heaton', 6, 'The Old Ma', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('486-55-04606-70-0', 'Scarlett Oatway', 4, ' Oedipus a', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('376-17-52371-77-6', 'Noah Mackenzie', 1, 'Great Expe', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('052-71-57282-07-7', 'William Abbot', 10, 'The Odysse', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('783-65-42710-18-3', 'Maria Michael', 8, 'Ulysses', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('458-22-06387-72-4', 'Alexander Kerr', 1, 'Don Quixot', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('528-66-17368-66-3', 'Aiden Todd', 11, 'Paradise L', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('057-12-82750-47-2', 'Julius Thomas', 8, 'The Red an', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('213-60-41136-04-7', 'Gil Hepburn', 10, 'The Metamo', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('563-32-22048-88-6', 'Mason Gilbert', 2, 'The Flower', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('750-78-04457-00-0', 'Emerald Nash', 10, 'Paradise L', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('146-46-13738-53-5', 'Daniel Allen', 9, 'Ulysses', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('426-65-13871-15-0', 'Vicky Baxter', 11, 'The Sun Al', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('354-21-50341-57-0', 'Jamie Hepburn', 2, 'Alice Adve', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('122-24-51244-73-1', 'Amy Jarvis', 9, 'One Thousa', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('405-68-62311-85-2', 'Bart Norburn', 11, 'The Great ', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('860-34-86630-53-7', 'Jocelyn Osmond', 5, 'Don Quixot', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('242-20-05743-56-3', 'Louise Reyes', 6, 'Gone With ', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('072-87-24703-70-6', 'Julianna Mcleod', 7, 'The Sun Al', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('838-01-36213-80-1', 'Luke Vass', 6, 'David Copp', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('384-24-45272-00-0', 'Chelsea Coll', 7, 'The Great ', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('050-82-30256-58-6', 'Erick Redfern', 8, 'The Great ', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('454-08-01286-37-8', 'Camila Wilkinson', 2, 'To the Lig', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('273-18-52322-61-3', 'Britney Carter', 1, 'Nineteen E', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('170-01-52763-77-2', 'Ellen Drew', 6, 'Gone With ', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('445-58-02586-68-7', 'Lorraine Palmer', 6, 'The Great ', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('246-64-84431-88-7', 'Meredith Speed', 9, 'The Scarle', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('008-03-08484-77-2', 'Mabel Hobbs', 3, 'The Sun Al', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('164-57-30683-23-4', 'Harry Strong', 9, 'The Odysse', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('354-44-85260-36-5', 'Ethan Khan', 6, 'Great Expe', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('052-30-15022-26-5', 'Luke Gaynor', 6, 'The Metamo', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('852-12-54561-32-3', 'Vera Hill', 3, 'Paradise L', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('428-82-03273-16-0', 'Georgia Flett', 4, 'Hamlet', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('865-48-78082-21-5', 'Rosalyn Mitchell', 6, 'The Sound ', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('808-26-25435-07-4', 'Nick Turner', 8, 'Pride and ', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('003-04-04241-14-3', 'Hanna Plant', 10, 'The Odysse', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('822-25-47375-23-1', 'Denny Anderson', 4, 'Game of Th', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('321-00-21050-25-7', 'Maggie Stevenson', 1, 'The Good S', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('755-55-52701-26-5', 'Mark Martin', 9, 'Oedipus', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('204-31-35034-83-4', 'Sharon Whatson', 3, 'David Copp', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('547-40-83252-42-1', 'Leroy James', 7, 'Lolita', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('428-47-31675-74-8', 'Eduardo Edmonds', 3, 'Wuthering ', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('337-00-68161-07-0', 'Jack Attwood', 6, 'One Thousa', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('818-24-66753-61-6', 'Cassandra Walsh', 11, 'Paradise L', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('868-13-56760-56-1', 'Luke Harris', 4, 'Paradise L', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('222-82-78837-74-4', 'Rosie Gates', 2, 'Vanity Fai', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('467-80-68656-84-0', 'Logan Rixon', 11, 'The Great ', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('534-52-88510-05-4', 'Havana Walsh', 9, 'The Good S', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('222-13-14377-62-8', 'Celina Whitehouse', 3, 'One Hundre', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('401-07-54140-66-2', 'Denis Pond', 2, 'Hamlet', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('037-50-63714-88-6', 'Manuel White', 4, 'Nineteen E', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('447-08-20143-17-8', 'Carl Phillips', 2, 'Don Quixot', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('023-63-64007-87-5', 'Rylee Russel', 5, 'The Lord o', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('728-58-48587-38-5', 'Nicholas Moore', 4, 'The Scarle', 'Audio');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('434-20-35456-52-5', 'Adelaide Tobin', 10, 'The Old Ma', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('414-14-16824-60-4', 'Georgia Radcliffe', 9, 'Hamlet', 'Paper');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('822-82-73462-24-6', 'Henry Forth', 1, 'To the Lig', 'Digital');
INSERT INTO mtl.series (issn_s, Curator, Edition, NameS, AccessMode) VALUES ('803-32-07615-68-3', 'Nathan Chester', 3, 'Hamlet', 'Audio');