INSERT INTO mtl.author (fname, lname) VALUES ('Federico', 'Rossi'),
( 'Laura', 'Bianchi'),
( 'Marco', 'Neri'),
('Sara', 'Giordano'),
( 'Anna', 'Giordano'),
( 'Marco', 'Bianchi'),
('Laura', 'Ferrari'),
( 'Francesco', 'Verdi'),
('Chiara', 'Esposito'),
('Federica', 'Romano'),
( 'Joanne', 'Rowling '),
('Andrzej ', 'Sapkowski'),
( 'Ludovico', 'Lanz'),
('Andrea', 'Lacaita'),
( 'National', 'Geographic')

